name: Calcium
options:
  bundleIdPrefix: com.romanpodymov
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "16.2"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: 1.18.0
  BigNumber:
    url: https://github.com/mkrd/Swift-BigInt
    branch: master
  Resolver:
    url: https://github.com/hmlongco/Resolver
    version: 1.5.1
targets:
  CalciumApp:
    settings:
      base:
        SWIFT_VERSION: '6'
    type: application
    platform: iOS
    sources: [Calcium]
    dependencies:
      - framework: CalciumCommon/build/XCFrameworks/release/CalciumCommon.xcframework
      - package: ComposableArchitecture
      - package: BigNumber
      - package: Resolver
    info:
      path: Calcium/Info.plist
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
  CalciumAppTests:
    settings:
      base:
        SWIFT_VERSION: '6'
    type: bundle.unit-test
    platform: iOS
    sources: [CalciumTests]
    dependencies:
      - target: CalciumApp
    info:
      path: CalciumTests/Info.plist
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
