name: Calcium
options:
  bundleIdPrefix: com.romanpodymov
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "15.4"
targets:
  CalciumApp:
    type: application
    platform: iOS
    sources: [Calcium]
    info:
      path: Calcium/Info.plist
  CalciumAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [CalciumTests]
    dependencies:
      - target: CalciumApp
    info:
      path: CalciumTests/Info.plist
